### ISSUE TITLE
__init__.py in .gitignore

### ISSUE THREAD

**Issue by Mat001** [Lamden/vmnet#4]
Hey @wywfalcon ,

I know you're a busy man...

I wonder why did you put `__init__.py` into .gitignore? 
Is there a reason?
(When I clone vmnet I get import issues.)

Cheers

**Comment by wywfalcon** [comment]
noted, we got too accustomed to python3 and I just got excited. Haha, let me put it back in.

**Comment by Mat001** [comment]
Cool!
Can I ask you, is vmnet is a working state right now? Does it work for you when you run example in readme? I'm hitting an error and wondering if it's actually in a working state or not? Thx Falcon

**Comment by wywfalcon** [comment]
sorry, it seems that the image-build is not working now and we need to add seneca for the new image. Due to MariaDB 10.2 now including RocksDB out of the box, we can now have a more stable image build. Also I'll be using alpine as it is smaller and now overall simpler. Let me update you once things become stable.
